# Generated by Django 5.2.3 on 2025-09-16 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_file_original', models.FileField(upload_to='videos/original/')),
                ('video_file_1080p', models.FileField(blank=True, null=True, upload_to='videos/1080p/')),
                ('video_file_720p', models.FileField(blank=True, null=True, upload_to='videos/720p/')),
                ('video_file_360p', models.FileField(blank=True, null=True, upload_to='videos/360p/')),
                ('video_file_120p', models.FileField(blank=True, null=True, upload_to='videos/120p/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='previews/')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.genre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
