# Generated by Django 5.2.4 on 2025-11-11 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file_1080p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file_120p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file_360p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file_720p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file_original',
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(choices=[('original', 'Original'), ('1080p', '1080p'), ('720p', '720p'), ('360p', '360p'), ('120p', '120p')], max_length=10)),
                ('file', models.FileField(upload_to='videos/')),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bitrate', models.PositiveIntegerField(blank=True, help_text='Bitrate in kbps', null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video File',
                'verbose_name_plural': 'Video Files',
                'ordering': ['video', 'resolution'],
                'unique_together': {('video', 'resolution')},
            },
        ),
    ]
